# Generated by Django 4.1 on 2022-08-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algs', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='Просто так', max_length=125, verbose_name='Название заметки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('add', 'Дополнение')], default='add', max_length=50, verbose_name='Тип заметки'),
        ),
    ]
